- package.json
- src/shared/ui/RadioGroup/RadioGroup.module.scss
- src/shared/ui/RadioGroup/RadioGroup.stories.tsx
- src/shared/ui/RadioGroup/RadioGroup.tsx
- src/shared/ui/RadioGroup/index.ts
Реализован компонент RadioGroup для выбора одного варианта из нескольких с использованием радио-кнопок. 
- Настраиваемые опции для выбора
- Обработка и отображение ошибок
- Несколько вариантов отображения (Default, With Multiple Options, With Error, Disabled, Disabled Selected)
> JOY-4: add radio-group

- src/shared/ui/textArea/TextArea.tsx
- src/shared/ui/textArea/textArea.module.scss
- src/shared/ui/textArea/textArea.stories.tsx
Added new component - Text Area
> Joy 8 text area

- src/shared/ui/button/Button.module.scss
Небольшие правки в стили компонента Button. 
Обновлены CSS свойства (focus outline).
> JOY-7 fix: change styles

- src/shared/ui/selectBox/SelectBox.module.scss
- src/shared/ui/selectBox/SelectBox.stories.tsx
- src/shared/ui/selectBox/SelectBox.tsx
Изменила структуру компонента - теперь SelectItem можно экспортировать и стилизовать отдельно, пофиксила баг в стилях при hover
> fix: export SelectItem instead of options

- src/shared/ui/button/Button.module.scss
- src/shared/ui/button/Button.stories.tsx
- src/shared/ui/button/Button.tsx
- src/shared/ui/index.ts
Пофиксила стайлы для Button при hover, active, focus
Добавила свои компоненты в общий index.ts
> fix-button fix: styles hover, active, focus

- src/shared/UI/card/index.ts
- src/shared/UI/pagination/Pagination.tsx
- src/shared/UI/pagination/index.ts
- src/shared/UI/pagination/pagination.module.scss
- src/shared/UI/textArea/index.ts
- src/shared/ui/textArea/TextArea.tsx
Fix pagination and added index.ts files for exports in pagination, card and text area components
> Fix pagination

- src/shared/ui/label/Label.tsx
- src/shared/ui/textField/TextField.tsx
Добавила экспорт типа TextField чтобы его можно было использовать в FormTextField
Скорректировала пропсы у label
> fix: label props, export type from input

- src/shared/ui/button/Button.module.scss
Исправлены стили в зависимости от значения атрибута as
> fix-button: fix styles

- src/features/auth/utils/schemas/EmailSchema.ts
- src/features/auth/utils/schemas/PasswordSchema.ts
- src/features/auth/utils/schemas/SignupSchema.ts
Added schemas that can be re-used in other components:
-EmailSchema
-PasswordSchema
> fix: added schema for password and email

- src/shared/ui/sidebar/Sidebar.module.scss
- src/shared/ui/sidebar/Sidebar.stories.tsx
- src/shared/ui/sidebar/Sidebar.tsx
- src/shared/utils/SidebarItem/SidebarItem.tsx
Реализована новая версия компонента Sidebar с поддержкой двух вариантов рендеринга:
1. Рендеринг через передачу children
2. Рендеринг через передачу массива items
3. Добавлен onClick для каждого items
Основные изменения:
1. Добавлена функция createSidebarItems для генерации элементов sidebar
2. Поддержка ролей пользователей (user/admin)
> sidebar: fix onClick items

- src/shared/ui/header/Header.module.scss
- src/shared/ui/header/Header.tsx
> JOY-48 fix: header refactor

- src/app/layout.module.scss
- src/app/layout.tsx
- src/app/page.tsx
- src/app/styles/boilerplate.css
- src/shared/ui/datePicker/DatePicker.tsx
- src/shared/ui/header/Header.module.scss
Add mainContainer to RootLayout and set max-width on it.
Remove max-width from main.
Add 'use client' to DatePicker
> JOY-49 fix: modify root layout styling

- src/app/auth/github/login-success/page.tsx
- src/app/auth/login/page.tsx
- src/app/auth/oauth-сallback/page.tsx
- src/app/auth/registration/page.tsx
- src/app/auth/verify-email/page.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/features/auth/api/authApi.ts
- src/features/auth/ui/login/Login.tsx
- src/features/auth/ui/signupForm/SignupForm.tsx
- src/features/auth/ui/socialLinks/SocialLinks.tsx
- src/features/auth/ui/socialLinks/socialLinks.module.scss
- src/shared/api/baseQueryWithReauth.ts
- src/shared/ui/button/Button.module.scss
- src/shared/ui/form/Form.tsx
- src/shared/ui/header/Header.tsx
- src/shared/ui/sidebar/Sidebar.module.scss
- src/shared/ui/sidebar/Sidebar.tsx
В этом PR внесены следующие изменения:
- Добавлены стили для иконок.
- Исправлены стили сайдбара при active.
- Перенесены сайдбар и кнопку очищения данных на главную страницу (временно, пока нет logout).
- В хедере добавлены рабочие ссылки.
- В форму добавлено свойство `disabled`.
- Добавлено OAuth 2.0 для гитхаба с минимальной логикой (подправлю позже, после запроса '/auth/me')
> Joy 22 add: registration and login via GitHub

- src/app/auth/login/page.tsx
- src/features/auth/ui/login/Login.stories.tsx
- src/features/auth/ui/login/Login.tsx
- src/features/auth/ui/login/login.module.scss
Added handleLogin function to login page
> JOY-19-fix: login request

- src/app/page.tsx
- src/features/auth/ui/logout/LogoutModal.tsx
- src/features/auth/ui/logout/logoutModal.module.scss
> JOY-21-Log-out

- src/app/(pages)/create/page.tsx
- src/app/(pages)/favorites/page.tsx
- src/app/(pages)/messenger/page.tsx
- src/app/(pages)/profile/page.tsx
- src/app/(pages)/search/page.tsx
- src/app/(pages)/settings/page.tsx
- src/app/(pages)/statistics/page.tsx
- src/app/MainLayout.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/shared/ui/header/Header.module.scss
- src/shared/ui/header/Header.tsx
- src/shared/ui/loader/Loader.module.scss
- src/shared/ui/sidebar/Sidebar.module.scss
- src/shared/ui/sidebar/Sidebar.tsx
- src/shared/utils/sidebarItem/SidebarItem.tsx
- src/styles/layout.module.scss
1. Добавлены страницы-заглушки для сайдбара
2.  Создан MainLayout.tsx (общий шаблон (каркас) для всех страниц, чтобы не повторять одно и то же на каждой из них.) 
- Показывает Header — всегда сверху.
- Показывает Sidebar, если пользователь авторизован.
- Показывает модалку выхода (LogoutModal), если нужно.
- Показывает Loader, если идёт переход между страницами.
- Внутрь помещает саму страницу (children) — например, профиль, главную и т.д.
3. Исправлен activePath для сайдбара
> refactor: restructure project folders

- src/app/MainLayout.tsx
- src/features/auth/ui/logout/LogoutModal.tsx
- src/shared/utils/sidebarItem/SidebarItem.tsx
> JOY-21 feat: add logout logic within previous updates

- src/app/MainLayout.tsx
- src/app/providers/AuthProvider.tsx
- src/features/auth/hooks/useOAuthLogin.ts
- src/features/auth/ui/authGuard/AuthGuard.tsx
- src/features/auth/ui/oauthLoginSuccess/OauthLoginSuccess.tsx
- src/features/auth/ui/socialLinks/SocialLinks.tsx
- src/shared/config/messages.ts
- src/shared/ui/sidebar/Sidebar.module.scss
- src/shared/ui/sidebar/Sidebar.stories.tsx
- src/shared/ui/sidebar/Sidebar.tsx
- src/shared/utils/sidebarItem/SidebarItem.tsx
1.  Добавлены useCallback, useMemo
2. Изменена логика внутри компонент
3.  Доданы константы в messages.ts
> sidebar: fix components-logic

- src/app/auth/login/page.tsx
- src/features/auth/hooks/useLogout.ts
- src/features/auth/ui/signupForm/SignupForm.tsx
- src/shared/api/baseQueryWithReauth.ts
- src/shared/ui/form/Form.tsx
- src/shared/utils/handleErrors/handleErrors.ts
-добавлена функция handleErrors для обработки всех ошибок в приложении
-убрана обработка ошибок в компонентах login /signupForm
> JOY61-feat: error handler added

- src/shared/ui/dropdownMenu/DropdownMenu.module.scss
- src/shared/ui/dropdownMenu/DropdownMenu.stories.tsx
- src/shared/ui/dropdownMenu/DropdownMenu.tsx
- src/shared/ui/dropdownMenu/DropdownMenuItem.tsx
- src/shared/ui/dropdownMenu/dropdownMenuItem/DropdownMenuItem.tsx
Add reusable DropdownMenu component
> JOY-73 feat: add dropdown menu

- src/shared/ui/modal/Modal.tsx
Исправлено отображение модалки, если нужно добавить ещё две иконки и по центру текст
> JOY-79: fix modal view

- CODEOWNERS
Попытка добавить автоматические отметки на ревью
> create: CODEOWNERS

- src/features/post/api/postsApi.ts
- src/features/post/ui/postModal/editPost/EditPostForm.module.scss
- src/features/post/ui/postModal/editPost/EditPostForm.tsx
- src/features/post/ui/postModal/editPost/index.ts
- src/features/post/ui/postModal/index.ts
- src/features/post/ui/postModal/postActions/PostActions.module.scss
- src/features/post/ui/postModal/postContent/PostContent.module.scss
- src/features/post/ui/postModal/postContent/PostContent.tsx
- src/features/post/ui/postModal/postContent/index.ts
- src/features/post/ui/postModal/postDropdownMenuItems/usePostDropdownMenuActions.ts
- src/features/post/ui/postModal/postModal/PostModal.module.scss
- src/features/post/ui/postModal/postModal/PostModal.tsx
- src/features/post/ui/postsGridWithInfiniteScroll/PostsGridWithInfinteScroll.tsx
- src/shared/api/joyfyApi.ts
- src/shared/ui/confirmModal/index.ts
- src/shared/ui/imageSlider/ImageSlider.tsx
- src/shared/ui/index.ts
- src/shared/ui/loader/index.ts
- src/shared/ui/modal/Modal.module.scss
- src/shared/ui/modal/Modal.tsx
- src/shared/ui/textArea/TextArea.tsx
- src/shared/ui/textArea/textArea.module.scss
- src/shared/ui/userCard/UserCard.tsx
Добавила редактирование поста.
Изменила PostModal, чтобы отображать пост и при редактировании - форму для редактирования поста.
Добавила запросы getPostById and editPost, для отображения и редактирования поста соответственно. При клике на изображение поста отправляется запрос на получение поста. При сохранении редактированного поста - происходит повторный запрос за обновленным постом.
Изменила модалку ConfirmModal, чтобы она обрабатывала как удаление поста, так и отмену редактирования. При закрытии PostModal в режиме редактирования также открывается ConfirmModal.
> JOY-43 feat: Edit post

- src/app/auth/(docs)/privacy-policy/page.tsx
- src/app/auth/(docs)/terms-of-service/page.tsx
- src/entities/auth/InfoPage.module.scss
- src/entities/auth/InfoPage.tsx
- src/entities/auth/PrivacyPolicy.tsx
- src/entities/auth/TermsAndServices.tsx
- Я сверсталь Terms and Services
- Я сверсталь Privacy Policy
> JOY-78 feat: info pages markup

- src/shared/ui/textArea/TextArea.tsx
- src/shared/ui/textArea/textArea.module.scss
- Изменил стили текстового поля, чтобы текст не выходил за его границы.
- Убедился, что текст остается в пределах поля на всех разрешениях экрана.
Раньше длинный текст выходил за края поля, ломая вёрстку. Теперь текст корректно переносится или обрезается.
> JOY-8 fix: prevent text from exceeding text area bounds

- src/app/MainLayout.tsx
Исправленно отображение сайбара когда пользователь не залогинен:
> JOY-89 fix: sidebar render fix

- src/app/(pages)/profile/[id]/page.tsx
- src/app/MainLayout.tsx
- src/features/post/api/postsApi.ts
- src/features/post/ui/postModal/PostModal.tsx
- src/features/post/ui/postModal/components/postDropdownMenuItems/usePostDropdownMenuActions.ts
Пофикшено - обновлён постАпи. 
При удалении обновляется кеш РТК и не делается https запрос к беку за всеми постами снова
Прокинул userId в ПостМодал -> кастомныйХук -> postApi где обновляю кеш по userId
> Joy 90 bug with deleting the post

- src/shared/ui/imageSlider/ImageSlider.tsx
- src/shared/ui/modal/Modal.tsx
Исправлены warning в компоненте Modal + ImageSlider
> JOY-94 fix: resolve modal/slider warning

- src/features/profile/ui/generalInformation/GeneralInformation.tsx
- src/features/profile/ui/generalInformation/createProfileForm/CreateProfileForm.module.scss
- src/features/profile/ui/generalInformation/createProfileForm/CreateProfileForm.tsx
- src/features/profile/ui/generalInformation/createProfileForm/index.ts
- src/shared/ui/selectBox/SelectBox.module.scss
- src/shared/ui/separator/Separator.module.scss
Добавила форму для заполнения профиля в Общей информации
> JOY-83 feat: Add ProfileForm in General Information

- Jenkinsfile
- src/app/(pages)/profile/[id]/page.tsx
- src/features/post/ui/postModal/PostModal.tsx
- src/features/profile/ui/generalInformation/profileInfoForm/ProfileInfoForm.module.scss
Сделал опимизацию промисов, сделал обновление в PostModal где рисуется всё в буферном vurrentPost который изначально берётся из пропсов, а потом уже из РТК. Поменял команду в дженкинсе для дальнейго деплоя
> JOY-91-Too-slow-runtime-while-requesting-profile

- src/styles/layout.module.scss
- src/widgets/header/Header.module.scss
- src/widgets/sidebar/Sidebar.module.scss
- починено отображение сайдбара вовремя бесконечно скролла
- теперь хэдер и сайдбар - фиксированные
- у сайдбара убран скроллбар по умолчанию- при уменьшении высоты экрана скроллить сайдбар можно но некрасивый скроллбар не появляется - в будущем можно добавить наш кастомный скроллбар
> JOY-104 fix: sidebar styles with infinite scroll

- src/features/profile/api/devicesApi.ts
- src/features/profile/api/devicesApi.types.ts
- src/features/profile/ui/devices/DeviceInfoCard.tsx
- src/features/profile/ui/devices/Devices.module.scss
- src/features/profile/ui/devices/Devices.tsx
- src/features/profile/ui/profileSettings/ProfileSettings.tsx
- src/shared/api/joyfyApi.ts
- src/widgets/sidebar/Sidebar.stories.tsx
Окно настроек Devices теперь отображает все сессии пользователя.
Current device это тот же самое что и первый в списке Active sessions и кнопка логаут вылогинивает пользователя как обычный Логаут.
Логаут же на других устройствах просто убирает из списка активных + показывает уведомление какой id сессиси завершён
Кнопка Terminate all other sessions работает так же только вылогинивает все кроме current device и так же показывает уведомление.
В отображении имеются всего лишь 4 иконки из React icon на основании ОС системы так как это единственный параметр который приходит для всех устройств
> Joy 124 devices

- src/features/post/api/postsApi.ts
- src/features/post/api/postsApi.types.ts
- src/features/postModal/postViewMode/PostFooter.tsx
- src/features/postModal/postViewMode/PostReactions.tsx
- src/features/postModal/postViewMode/PostViewMode.module.scss
Отображение лайков на публикациях
Добавлена возможность ставить лайки. Если пользователь авторизован - он может ставить лайк. Система изменяет количество лайков,
отображение аватарки трех последних
пользователей, которые поставили лайки, и
подсвечивает сердечко красньім цветом. Если лайк уже стоит, нажимая по "сердечку" пользователь убирает свой лайк
> feat: UC-5 done

- src/app/(pages)/search/page.tsx
- src/app/store/store.ts
- src/features/auth/ui/login/Login.tsx
- src/features/auth/ui/sentEmailModal/SentEmailModal.tsx
- src/features/userSearch/api/usersApi.ts
- src/features/userSearch/api/usersApi.types.ts
- src/features/userSearch/model/recentRequestSlice.ts
- src/features/userSearch/ui/User.tsx
- src/features/userSearch/ui/UserSearch.tsx
- src/features/userSearch/ui/UsersList.module.scss
- src/features/userSearch/ui/UsersList.tsx
- src/features/userSearch/ui/index.ts
- src/shared/ui/avatar/Avatar.module.scss
- src/shared/ui/avatar/Avatar.tsx
- src/shared/ui/loader/Loader.module.scss
- src/shared/ui/loader/Loader.tsx
- src/shared/ui/textField/TextField.module.scss
- src/shared/ui/textField/TextField.tsx
- Поиск юзеров.
- Отображение последних поисковых запросов (переходов по ссылке) хранится в слайсе, ибо на бэке эндпоинта для этого не нашла.
> JOY-117: Search Users

- src/features/comments/api/commentsApi.types.ts
- src/features/comments/styles/commentStyles.scss
- src/features/comments/ui/AnswerItem.module.scss
- src/features/comments/ui/AnswerItem.tsx
- src/features/comments/ui/CommentItem.module.scss
- src/features/comments/ui/CommentItem.tsx
- src/features/comments/ui/ReplyForm.tsx
Исправлена проблема в некорректном определении текущего пользователя при нажатии на кнопку answer
> JOY-128: fix user identification in answer
